### PR TITLE
Add Rewind/Fast Forward Jump Interval Preferences

### PR DESCRIPTION
**Pull request by KBerstene**
Adds preferences under Settings->Playback to allow users to set how far they want to rewind or fast forward.  Defaults are still set to 10s and 30s respectively, which is currently hard-coded.

For the record, I'm not really pleased with using Integer.parseInt(Util.getPreferences(this).getString(...)) instead of Util.getPreferences(this).getInt(...).  It's not really an elegant solution to cast it in this way, but it works.

### CODE REVIEW

**Comment by daneren2005** [comment]
I merged this into `edge`.  I have changed `edge` to be the main branch since it is where I am doing any active development and where I would like PR's merged into.  I am manually closing it since Github doesn't automatically close it until it is merged into `master` otherwise.

**Comment by KBerstene** [comment]
Scott,

Just to make sure I am pointing anything I do to the correct branch, should I point any bugfixes to master or should I just create PRs for the edge branch?

**Comment by daneren2005** [comment]
I would point any new branches you create to `edge`.  For your other open PR it is fine that is points to `master`.  There probably won't be any merge conflicts, and if there are I can take care of them.

**Comment by KBerstene** [comment]
Okay, I will continue to point any bug fixes to master and any other
feature changes to edge. Thanks for the clarification!

**Pull request closed without merging**
