### PR TITLE
Added support for libresonic

### PR DESCRIPTION
**Pull request by maxammann**
Heyho,

there is a new open fork of subsonic: https://github.com/Libresonic/libresonic
I'm not sure yet if there's more to do. Libresonic has the same API as subsonic 6.0-beta1.

### CODE REVIEW

**Comment by daneren2005** [comment]
Is there a good reason to do a new response type instead of just including the name as parameters so it doesn't break compatibility with everything?

**Comment by maxammann** [comment]
@daneren2005 not sure since I do not maintain libresonic(unofficial("Kang") of Subsonic), but I think it makes sense because you can not be sure how subsonic changes it's api since it's closed source now.

Let me know what you think.

**Comment by daneren2005** [comment]
When Libresonic was first forked someone approached me about this and I told them there was no reason to change to `libresonic-response` so they changed back at https://github.com/Libresonic/libresonic/commit/2cd4f34014c9d6f9710bd57d01e77f9e9130bac7.  Since they already made the sane decision to not break compatibility with no actual benefit I'm not going to accept this.

**Comment by maxammann** [comment]
k, thanks!

**Pull request closed without merging**
