### PR TITLE
WIP: Improve offline searching

### PR DESCRIPTION
**Pull request by fxthomas**
This PR tackles issue #636 :

- [x] Searching for parts of an album/artist/song work when offline
- [x] Search suggestions work when offline

### CODE REVIEW

**Comment by fxthomas** [comment]
I have a few additional questions :

* I added a `getPattern` method to the `SearchCriteria` class that seems awfully verbose for compiling the search query into a regular expression and handle wildcards in offline mode the same way as the Subsonic API. Is there something better I did not know about?
* Shouldn't `DSubSearchProvider` return an empty cursor if the query is empty, without even sending a request? It seems useless to search for _everything_, and in online mode the Subsonic API appears to be returning nothing anyway.

**Comment by daneren2005** [comment]
Is there a case where the query is passed empty to `DSubSearchProvider`?  I was under the impression that there would be no way to trigger that so I didn't bother implementing anything for that.  If you have nothing typed in the search results it shows nothing right now.  If there was a way to get it to show something when you first open up the search I would have it display search history instead of an empty set to be honest.

**Comment by daneren2005** [comment]
Also a side note, when working on DSub can you do tab indention instead of spaces?

**Comment by daneren2005** [comment]
Nevermind, you are right.  In offline mode if you type something then go backwards it does a empty query.  I can't get it to do that in online mode though.

**Comment by fxthomas** [comment]
I tried to keep the same indentation style as the original file, and `SearchCriteria.java` was using spaces (actually all files in `domain` are). I'll change it next time. Thanks for merging!

**Comment by daneren2005** [comment]
Yeah it's because the original code is and I never have changed a lot of those files

**Pull request merged**
