### PR TITLE
Fixed a bug with actionbar for podcast not always being correct

### PR DESCRIPTION
**Pull request by popeen**
The select_podcasts menu didn't load when opening the podcast view

### CODE REVIEW

**Comment by daneren2005** [comment]
I don't understand the purpose of this commit.  It looks like the only difference is now in offline mode/not as owner you will see the option "Check For New Episodes" but in offline mode it doesn't make sense and I am pretty sure that in stock Subsonic you require the Podcast permission to check for new episodes.

**Comment by popeen** [comment]
Good point. I thought it was for getting the latest episodes from the server but apparently not, Subsonic does indeed require permission for this check.
The reason for the commit is that normally the menu in the actionbar is not set as select_podcasts unless you enter a podcast and then go back or you turn the phone. Instead you get what I'm pretty sure is the abstract_top_menu. This is at least how it appears to work on my CM12 phone.

Offline/not owner problem should be fixed in second commit but I haven't been able to test it yet.

**Comment by daneren2005** [comment]
First off the check should be `Util.isOffline(context) || UserUtil.canPodcast()) == false` since you want to disable those if offline or you don't have permissions.

Second, I'm not understanding why that would behave differently.  Doing that should be functionally identical to what is already being done.  Instead of letting SelectRecyclerFragment handle it automatically you are just doing it in the parent class.  And instead of inflating the `abstract_top_menu` menu you are just pairing `select_podcasts` back to be identical.  The result should be the same though.  From a coding standpoint there is no functional difference between doing something in the abstract class vs doing it in the extended class.

The only functional difference I see is that you call `setHasOptionsMenu(true);` in the onCreate.  Can you check whether that is what is fixing it for you?  I can't reproduce the issue so I can't try it myself.

**Comment by daneren2005** [comment]
Also another thing to check is with the way I have it does changing UserUtils.java ```public static boolean isCurrentRole(String role) {
	return isCurrentRole(role, false);
}```

the default false to default true fix it?  I'm wondering if it is an issue with the user not being setup yet when you browse the fragment the first time.

**Comment by popeen** [comment]
Yes I know the abstract class should be able to handle it but for some reason that didn't seem to work so something must be messing with it. It seems to only happen when going to the fragment from the drawer, if I go from "a link" in the main fragment it works fine.

 When using just `hasOptionsMenu(true)` andr remocing onCreateOptonsMenu from the extended class it does get added yes but then you get it twice for some reason, I'm attaching a picture of what I mean. Setting the default value of isCurrentRole to true gives the same result as if it was false.

As for the if statement you are right. It should be `Util.isOffline(context) || !UserUtil.canPodcast()`. This time it's tested.

**Comment by daneren2005** [comment]
I finally had it happen to me and was able to reproduce it several times (no idea why all of a sudden it popped up for me).  I think I found a better across the board fix (since I was able to reproduce it on more than just the Podcasts tab) in e1df606624d9a18fde6ecb33c0647c2939a9b508.  Do you mind trying out my latest push and see if that fixes it for you?

**Comment by popeen** [comment]
Sure, I'll have a look at it as soon as I can. Will be sometime tomorrow.

**Comment by popeen** [comment]
No, problem seems to still be there. This is with the default admin account connected to Subsonic r4569

screenshot_2015-10-28-16-19-57

**Comment by popeen** [comment]
Just rebooted my phone and now it works fine. Will keep checking the app from time to time to see if it changes back to not working.

**Comment by popeen** [comment]
I have been doing some testing and it seems to work like this.

If I force stop & clear the data or do a fresh install it will stop working. Once I reboot the phone it works again. Just force stopping the app and then starting it again does not work, it needs to be phone reboot.

**Comment by daneren2005** [comment]
Apparently I was not refreshing the current user details unless the server instance changed. It should have refreshed when force closing the app and did for me. I am wondering if it is some part of CM is not actually destroying static variables when force closed. I fixed it so that when you change the server details it will refresh the users details. Sorry about the long back and forth but this has helped me find some edge case bugs in the process. Let me know if this fixed it for you.

**Comment by popeen** [comment]
No problem about the back and forth, in the end it means I get a better app (well two since I can merge it to booksonic) so I'm happy about it.  

The app is working better but still not 100%.
If I add a new server it works fine but if I modify the subsonic demo server to use my details it doesn't. 

Force closing the app seems to make it update now as well.

**Pull request closed without merging**
