### PR TITLE
Change raw music stream to use 'download'

### PR DESCRIPTION
**Pull request by brian-doherty**
When raw music stream is called for, changed to use 'download' instead of 'stream' to accommodate servers with older API versions (e.g. Gonic).

### CODE REVIEW

**Comment by brian-doherty** [comment]
@daneren2005 Would really appreciate it if you could have a look at this one. It's a pretty small change.

**Comment by daneren2005** [comment]
So why is this needed? What is different about using download instead of stream for the end server?

**Comment by brian-doherty** [comment]
You're issuing stream with a bitrate which causes an unnecessary transcode.
Necessary is a strong word but I would say desirable.

**Comment by sentriz** [comment]
for me it seems dsub sends along a `format=raw` param when casting, when gonic sees that it shouldn't transcode

https://github.com/sentriz/gonic/blob/bf3c13b56843dadac0e7527901d9ab388cd96307/server/ctrlsubsonic/handlers_raw.go#L308-L311

just tested on my chromecast and seems to work

also IIRC i've seen dsub send a maxBitrate which is equal to the track bitrate - gonic won't transcode in that case either

PS i wasn't familiar with the different API versions regarding stream.view/download.view has there been an update to the API that gonic doesn't support?

EDIT

also then, what should be the difference between download.view and stream.view?format=raw ?

**Comment by brian-doherty** [comment]
I saw ffmpeg running. I wonder if there was a rounding / bitrate detection
issue? I'll be honest -- it's been a while since I submitted this so maybe
a gonic change obviated the need for it.

**Comment by sentriz** [comment]
the change was made in september so maybe could be worth testing again

i'm still wondering if gonic is using an old version of the api for stream/download

but maybe that's not an issue for this repo :grin:

**Comment by brian-doherty** [comment]
OK I tried it and I don't see that behavior anymore. Will close.

**Comment by daneren2005** [comment]
Sorry about not getting back to this earlier.  It seemed pretty simple but from my understanding of the server it also seemed like it shouldn't be necessary and then I kept forgetting to ask for what it was for.  Glad to hear it is no longer needed now.

**Pull request closed without merging**
